apiVersion: apps/v1
kind: Deployment
metadata:
  name: opti-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opti-backend
  template:
    metadata:
      labels:
        app: opti-backend
    spec:
      containers:
        - name: opti-backend
          image: makprodevel/opti-backend
          ports:
            - containerPort: 8000
          env:
            - name: release
              value: "yes"
            - name: db_host
              value: {{ .Release.Name }}-postgresql
            - name: db_pass
              value: {{ .Values.postgresql.auth.postgresPassword }}
            - name: redis_url
              value: redis://{{ .Release.Name }}:6379
          readinessProbe:
            httpGet:
              path: /api/
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: opti-backend-service
spec:
  selector:
    app: opti-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP