apiVersion: apps/v1
kind: Deployment
metadata:
  name: opti-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opti-backend
  template:
    metadata:
      labels:
        app: opti-backend
    spec:
      containers:
        - name: opti-backend
          image: makprodevel/opti-backend
          ports:
            - containerPort: 8000
          env:
            {{ include "opti.env.release" . | nindent 12 }}
            {{ include "opti.env.postgresql" . | nindent 12 }}
            {{ include "opti.env.redis" . | nindent 12 }}
            {{ include "opti.env.googleClientId" . | nindent 12 }}
            {{ include "opti.env.secretKey" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
      initContainers:
        - name: alembic-migrations
          image: makprodevel/opti-backend
          command: ["python", "-m", "poetry", "run", "alembic", "upgrade", "head"]
          env:
            {{ include "opti.env.release" . | nindent 12 }}
            {{ include "opti.env.postgresql" . | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: opti-backend-service
spec:
  selector:
    app: opti-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP