apiVersion: apps/v1
kind: Deployment
metadata:
  name: opti-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opti-frontend
  template:
    metadata:
      labels:
        app: opti-frontend
    spec:
      containers:
        env:
          - name: VITE_GOOGLE_CLIENT_ID
            value: 387912847310-8l3qtrn530qtkgcoc1r86cu2tafn1scg.apps.googleusercontent.com
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: opti-frontend-service
spec:
  selector:
    app: opti-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
