apiVersion: apps/v1
kind: Deployment
metadata:
  name: opti-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opti-frontend
  template:
    metadata:
      labels:
        app: opti-frontend
    spec:
      containers:
        - name: opti-frontend
          image: makprodevel/opti-frontend
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: opti-frontend-service
spec:
  selector:
    app: opti-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
