apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opti-ingress
spec:
  rules:
    - host: opti-app.serveo.net
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: opti-backend-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opti-frontend-service
                port:
                  number: 80
