env:
  postgresHost: POSTGRESQL_HOST
  postgresPass: POSTGRESQL_PASS
  redisUrl: REDIS_URL
  googleClientIdKey: GOOGLE_CLIENT_ID
  googleClientIdValue: 387912847310-8l3qtrn530qtkgcoc1r86cu2tafn1scg.apps.googleusercontent.com
  secretKey: SECRET_KEY
  secretValue: somestr
  releaseKey: RELEASE
  releaseValue: release

postgresql:
  auth:
    database: opti
    postgresPassword: passme
  primary:
    initdb:
      scripts:
        00_init_extensions.sql: |
          CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
          CREATE EXTENSION IF NOT EXISTS pg_trgm;

redis:
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false
    replicaCount: 1
